# Generated by Django 4.1.3 on 2022-12-04 16:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='blog_comment',
            fields=[
                ('comment', models.TextField()),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='author.author')),
            ],
        ),
        migrations.CreateModel(
            name='blog_post_level',
            fields=[
                ('level', models.CharField(max_length=100)),
                ('icon', models.ImageField(upload_to='static/admin_static_datablog_post_level_icons')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='blog_tag',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='blog_post_category',
            fields=[
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('icon', models.ImageField(upload_to='static/admin_static_datablog_post_category_icons')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('tags', models.ManyToManyField(to='blog.blog_tag')),
            ],
        ),
        migrations.CreateModel(
            name='blog_post',
            fields=[
                ('title', models.CharField(max_length=100)),
                ('tech_title', models.CharField(max_length=100)),
                ('cover', models.ImageField(upload_to='static/users_static_datablog_post_covers')),
                ('preview', models.TextField()),
                ('body', models.TextField()),
                ('views', models.IntegerField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='author.author')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blog_post_category')),
                ('comments', models.ManyToManyField(to='blog.blog_comment')),
                ('thread', models.ManyToManyField(blank=True, to='blog.blog_post')),
            ],
        ),
    ]
