# Generated by Django 4.1.3 on 2022-12-01 18:40

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0004_remove_author_level_author_bio_skill_level_author'),
        ('blog', '0002_remove_blog_comment_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='blog_post_level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=100)),
                ('icon', models.ImageField(upload_to='static/users_upload_post_files')),
            ],
        ),
        migrations.RemoveField(
            model_name='blog_post',
            name='tags',
        ),
        migrations.AddField(
            model_name='blog_post',
            name='thread',
            field=models.ManyToManyField(blank=True, to='blog.blog_post'),
        ),
        migrations.AddField(
            model_name='blog_tag',
            name='color',
            field=colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=18, samples=None),
        ),
        migrations.AlterField(
            model_name='blog_comment',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='author.author'),
        ),
        migrations.AlterField(
            model_name='blog_comment',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.blog_post'),
        ),
        migrations.CreateModel(
            name='blog_post_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('icon', models.ImageField(upload_to='static/users_upload_post_files')),
                ('post', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.blog_post')),
            ],
        ),
        migrations.AddField(
            model_name='blog_tag',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.blog_post_category'),
        ),
    ]
