# Generated by Django 4.1.3 on 2022-11-29 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_tag_blog_post_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_post',
            name='cover',
            field=models.ImageField(upload_to='static/user_upload'),
        ),
    ]
