# Generated by Django 4.1.3 on 2022-11-29 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blog_post_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_post',
            name='preview',
            field=models.TextField(),
        ),
    ]
