# Generated by Django 4.1.3 on 2022-12-04 16:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='skill_level',
            fields=[
                ('skill_level', models.CharField(blank=True, max_length=50, null=True)),
                ('skill_icon', models.ImageField(blank=True, null=True, upload_to='static/admin_static_dataskill_level_icon')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='user_class',
            fields=[
                ('user_class', models.CharField(blank=True, max_length=100, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='author',
            fields=[
                ('nickname', models.CharField(max_length=20)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='static/users_static_dataauthor_avatar')),
                ('headline', models.TextField(blank=True, max_length=200)),
                ('speciality', models.CharField(blank=True, max_length=50)),
                ('bio', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('facebook', models.CharField(blank=True, max_length=100, null=True)),
                ('twitter', models.CharField(blank=True, max_length=100, null=True)),
                ('linkedin', models.CharField(blank=True, max_length=100, null=True)),
                ('registration', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('skill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='author.skill_level')),
                ('user_class', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='author.user_class')),
            ],
        ),
    ]
