# Generated by Django 4.1.3 on 2022-11-30 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=20)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='static/users_upload_avatars')),
                ('headline', models.TextField(blank=True, max_length=100)),
                ('speciality', models.TextField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('facebook', models.CharField(blank=True, max_length=100, null=True)),
                ('twitter', models.CharField(blank=True, max_length=100, null=True)),
                ('linkedin', models.CharField(blank=True, max_length=100, null=True)),
                ('registration', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
