# Generated by Django 4.1.3 on 2022-11-29 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=50)),
                ('registration', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
