# Generated by Django 4.1.3 on 2022-11-30 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='headline',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='author',
            name='speciality',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
