# Generated by Django 4.1.3 on 2022-11-30 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0002_alter_author_headline_alter_author_speciality'),
    ]

    operations = [
        migrations.CreateModel(
            name='skill_level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_level', models.CharField(blank=True, max_length=50, null=True)),
                ('skill_icon', models.ImageField(blank=True, null=True, upload_to='static/users_upload_avatars')),
            ],
        ),
        migrations.AddField(
            model_name='author',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='author.skill_level'),
        ),
    ]
