# Generated by Django 4.1.3 on 2022-12-01 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0003_skill_level_author_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='level',
        ),
        migrations.AddField(
            model_name='author',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='skill_level',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='author.author'),
        ),
    ]
