# Generated by Django 4.1.3 on 2022-12-04 16:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='news',
            fields=[
                ('date', models.DateTimeField(auto_created=True)),
                ('title', models.CharField(max_length=100)),
                ('preview', models.TextField(max_length=300)),
                ('cover', models.ImageField(upload_to='static/admin_static_datanews_cover')),
                ('body', models.TextField()),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
