name: "Pull changes from repo to VPS"
on: workflow_dispatch
env:
  PROJECT_DIR: /var/www/pyoops.com/

jobs:
  pull_changes_to_vps:
    runs-on: ubuntu-latest

    steps:
      - name: Download VPS IP artifact and check it
        uses: actions/download-artifact@v3
        with:
          workflow: create_vps_and_deploy.yml
          workflow_conclusion: success
          name: VPS IP
          
      - shell: bash
        run: |
          echo "VPS_IP=$(tail -1 ${{ env.vps_ip_file }})" >> $GITHUB_ENV
      - run: |
          echo ${{ env.VPS_IP }}


      - name: "Pull changes from repo to VPS"
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.VPS_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ${{ env.PROJECT_DIR }}
            git pull
