name: Testing create VPS
on: workflow_dispatch

jobs:
  create_vps:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout the repo"
        uses: actions/checkout@v3
      - name: "Setup Python and run the VPS create script"
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      - run: |
          pip install requests
          python3 ./1cloud_create_vps.py ${{ secrets.API_KEY }}