name: Work with env
on: workflow_dispatch

env:
  vps_ip_file: VPS_IP.txt

jobs:
  create_env:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Run Python scr
        run:
          python3 ./working_with_git_env.py

      - name: Save VPS IP to file and check
        run: |
          echo "VPS=${{ env.VPS }}" > ${{ env.vps_ip_file }}
          echo $(tail -1 ${{ env.vps_ip_file }})

      - name: Save VPS IP
        uses: actions/upload-artifact@v3
        with:
          name: VPS IP
          path: ${{ env.vps_ip_file }}

  read_env:
    needs: "create_env"
    runs-on: ubuntu-latest
    steps:
      - name: Read the value
        uses: actions/download-artifact@v3
        with:
          name: VPS IP
      - shell: bash
        run:
          echo $(tail -1 ${{ env.vps_ip_file }})
