name: Work with env
on: workflow_dispatch

jobs:
  read_env:
    runs-on: ubuntu-latest
    steps:
      - name: Set the value
        run:
          echo "action_state=yellow" >> $GITHUB_ENV
      - name: Use the value
        run:
          echo "${{ env.action_state }}"