name: Work with env
on: workflow_dispatch

jobs:
  create_env:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Run Python scr
        run:
          python3 ./working_with_git_env.py

  read_env:
    runs-on: ubuntu-latest
    steps:
      - name: Read the value
        run:
          echo "${{ env.VPS }}"