name: Work with env
on: workflow_dispatch

jobs:
  read_env:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "VPS=image" >> $GITHUB_ENV 
          echo "============"
          echo ${{env.VPS}}
          echo "============"