name: Work with env
on: workflow_dispatch

jobs:
  create_env:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Run Python scr
        run:
          python3 ./working_with_git_env.py

      - name: Save VPS IP to file and check
        run: |
          echo ${{ env.VPS }} > VPS_IP.txt
          echo $(tail -1 VPS_IP.txt)

      - name: Save VPS IP to repo
        uses: actions/upload-artifact@v3
        with:
          name: VPS IP
          path: VPS_IP.txt

  read_env:
    needs: "create_env"
    runs-on: ubuntu-latest
    steps:
      - name: Read the value
        uses: actions/download-artifact@v3
        with:
         name: VPS IP
      - shell: bash
        run: |
          echo $(tail -1 VPS_IPs.txt) >> /etc/profile
          source /etc/profile

      -run:
        echo ${{ env.VPS }}    
